
#ifndef PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_ERROR_H
#define PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_ERROR_H

#define ASSEMBLER_SUCCESS 0
#define ASSEMBLER_FAILURE -1
#define ASSEMBLER_INCORRECT_FILENAME -2
#define ASSEMBLER_OUT_OF_MEMORY -3

#endif //PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_ERROR_H
