#ifndef PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_H
#define PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_H


#define CODE_TABLE_START_ADDRESS 100
#define OPCODES_TABLE_LENGTH 16

#endif //PSYCHIC_OCTO_MEMORY_ASSEMBLER__ASSEMBLER_H
